export const SKILLS_MAP = {
  vue: 'Vue',
  nuxt: 'Nuxt',
  react: 'React',
  ts: 'TypeScript',
  js: 'JavaScript',
  rust: 'Rust',
  shell: 'Shell',
  elixir: 'Elixir',
  go: 'Go',
  html: 'HTML',
  css: 'CSS',
  scss: 'Sass',

  node: 'Node.js',
  express: 'Express.js',
  phoenix: 'Phoenix',
  rest: 'REST API',
  oauth: 'OAuth2',
  websockets: 'WebSockets',

  mongo: 'MongoDB',
  postgres: 'PostgreSQL',
  dynamodb: 'DynamoDB',
  questdb: 'QuestDB',
  sqlite: 'SQLite3',
  neo4j: 'Neo4j',
  snowflake: 'Snowflake',

  vuex: 'Vuex',
  pinia: 'Pinia',
  redux: 'Redux',
  saga: 'Redux Saga',

  tailwind: 'Tailwind CSS',
  vuetify: 'Vuetify',
  material: 'Material UI',

  docker: 'Docker',
  ansible: 'Ansible',
  aws: 'AWS',
  amplify: 'AWS Amplify',
  s3: 'AWS S3',
  cognito: 'AWS Cognito',
  kubernetes: 'Kubernetes',
  linux: 'Linux',
  proxmox: 'Proxmox',

  git: 'Git',
  npm: 'npm',
  vite: 'Vite',
  webpack: 'Webpack',
  figma: 'Figma',
  jira: 'Jira',
  confluence: 'Confluence',
  asana: 'Asana',
  trello: 'Trello',

  macroquad: 'Macroquad',
  wasm: 'WebAssembly',
  heroku: 'Heroku',
  oauth2: 'OAuth2',
  spa: 'SPA',
  ssr: 'SSR',
  
  // Added from jobs/projects
  github: 'GitHub',
  pages: 'GitHub pages',
  ci: 'CI/CD',
  seo: 'SEO',
  networking: 'Networking',
  dns: 'DNS',
  accessibility: 'Accessibility',
  responsive: 'Responsive Design',
  ux: 'UX/UI Design',
  crud: 'CRUD',
  caching: 'Caching',
  analytics: 'Analytics',
  qa: 'QA Testing',
  spotify: 'Spotify API',
  agile: 'Agile',
  wireframe: 'Wireframing'
}