import type { WorkExperienceData } from "@/types"
import { LINKS, SKILLS } from './index'

const { 
  vite, 
  nuxt, 
  spa, 
  seo, 
  pages,
  ci,
  accessibility,
  vuex,
  pinia,
  ts,
  websockets,
  crud,
  caching,
  ux,
  linux,
  proxmox,
  ansible,
  vue,
  js,
  css,
  responsive,
  analytics,
  qa,
  git,
  react,
  node,
  mongo,
  cognito,
  express,
  html,
  shell,
  questdb,
  go,
  elixir,
  phoenix,
  scss,
  sqlite,
  neo4j,
  vuetify,
  docker,
  tailwind, 
  figma,
  npm,
  ssr,
  gitlab,
  wireframe,
  asana,
  aws,
  amplify,
  s3,
  dynamo,
  graphql,
  snowflake,
  mysql,
  github,
  redux,

} = SKILLS

export const WORK_EXPERIENCE: WorkExperienceData[] = [
  {
    company: 'Hinkle Inspection and Testing',
    role: 'Lead Product Engineer and UX',
    location: 'Austin, TX',
    period: 'Sep 2025 - Present',
    description: 'Planned, designed, and shipped a modern digital presence for a Certified Welding Inspector to drive quote requests and establish credibility.',
    achievements: [
      'Drove discovery and created decision matrices for framework, hosting, images, and quote flow',
      'Planned architecture and shipped a production-ready single-page site end to end',
      'Designed responsive UI/UX focused on service clarity and client conversion',
      'Built a Vue 3 + Vite SPA in TypeScript, no backend dependency',
      'Implemented a quote workflow with mailto fallback, hosted form, and serverless adapter',
      'Delivered accessibility checks, SEO metadata, Open Graph, LocalBusiness schema, and GitHub Pages CI with custom domain and HTTPS'
    ],
    website: LINKS.COMPANIES.HINKLE,
    brandColors: ['#1e3a8a', '#3b82f6'],
    skills: [
      vue,
      vite, 
      spa, 
      ts, 
      ux, 
      wireframe,
      figma,
      ci, 
      responsive, 
      accessibility,
      seo,
      git,
      github,
      pages, 
    ]
  },
  {
    company: 'Rhodium Enterprises LLC',
    role: 'Software Engineer',
    location: 'Rockdale, TX (remote)',
    period: 'Dec 2022 - May 2025',
    description: 'Rhodium is a vertically integrated, Texas-based Bitcoin mining company pioneering energy-efficient, high-density mining through proprietary liquid-cooled infrastructure.',
    achievements: [
      'Led frontend architecture and UX/UI design across multiple internal dashboards, emphasizing modularity and scalability',
      'Optimized data handling through selective parsing and caching, reducing dataset size from 70MB to 2MB',
      'Implemented real-time systems using WebSockets for event tracking and state updates',
      'Built robust CRUD systems and managed workflows end-to-end from design to deployment'
    ],
    website: LINKS.COMPANIES.RHDM,
    brandColors: ['#181818','#C0A818', '#E0C850', '#E8D860'],
    skills: [
      vue, 
      nuxt,
      node,
      questdb,
      vuex,
      pinia,
      vuetify,
      tailwind, 
      ts,
      go,
      docker,
      elixir,
      phoenix,
      scss,
      sqlite,
      mongo,
      neo4j,
      html,
      css,
      websockets, 
      crud, 
      caching, 
      ux, 
      analytics, 
      linux,
      shell,
      proxmox, 
      ansible,
      git,
      figma,
      npm,
      gitlab,
      ssr,
      asana,
    ]
  },
  {
    company: 'NextIQ',
    role: 'Software Developer',
    location: 'Austin, TX',
    period: 'Feb 2022 - Sep 2022',
    description: 'NextIQ is a startup platform educating individuals and companies in the renewable energy sector through video content and tutorials from industry leaders.',
    achievements: [
      'Created and maintained website pages, components and user workflows',
      'Curated analytics and metrics of user activity to guide data-driven decisions',
      'Ensured responsive design across all device dimensions',
      'Implemented QA processes and collaborated across departments to eliminate bugs'
    ],
    website: LINKS.COMPANIES.NEXTIQ,
    brandColors: ['#F0B840', '#000000'],
    skills: [
      react,
      dynamo,
      aws,
      ts,
      redux,
      amplify,
      cognito,
      s3,
      graphql,
      snowflake,
      css,
      html,
      responsive,
      analytics,
      qa,
      git,
      gitlab,

    ]
  },
  {
    company: 'DevMountain',
    role: 'Full Stack Student Developer',
    location: 'Lehi, UT (remote)',
    period: 'May 2021 - Sep 2021',
    description: 'Intensive full-stack development bootcamp certification program.',
    website: LINKS.COMPANIES.DEVMOUNTAIN,
    achievements: [
      'Completed comprehensive curriculum covering frontend and backend technologies',
      'Built full-stack applications using modern web development frameworks',
      'Developed and recognized for collaborative coding and project management skills'
    ],
    brandColors: ['#20A8E0', '#383838'],
    skills: [js,
      react,
      node,
      mysql,
      express,
      mongo,
      shell,
      html,
      css,
      git,
      github,
    ]
  }
]